repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
        args: [--allow-multiple-documents]
    -   id: end-of-file-fixer
        exclude: (^tests/fixtures/)
    -   id: trailing-whitespace
# Enforce code style
-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    -   id: black
# Linting
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
# Static type checking
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
    -   id: mypy
        additional_dependencies:
        -    PyYAML
        -    aiohttp
        -    selenium
        -    flask

        args: [--explicit-package-bases]
