name: Run build.py

on:
  workflow_dispatch:

jobs:
  {% for i in range(total_jobs) %}
  build{{ i }}:
    {% if i > 0 %}
    needs: build{{ i - 1 }}
    {% endif %}
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install poetry
        poetry config virtualenvs.create false
        poetry install
    {% if i > 0 %}
    - name: Download database
      uses: actions/download-artifact@v4
      with:
        name: arcade-{{ date_time }}-{{ i - 1 }}.db
    {% endif %}
    - name: Run build.py
      run: |
        {% if i > 0 %}mv arcade-{{ date_time }}-{{ i - 1 }}.db arcade-{{ date_time }}-{{ i }}.db{% endif %}
        python -u build.py -p arcade-{{ date_time }}-{{ i }}.db -d {{ dat_type }} -s {{ jobs[i][0] }} {% if jobs[i][1] %} -e {{ jobs[i][1] }} {% endif %}

    - name: Upload database
      uses: actions/upload-artifact@v4
      with:
        name: arcade-{{ date_time }}-{{ i }}.db
        path: arcade-{{ date_time }}-{{ i }}.db
  {% endfor %}
